AWSTemplateFormatVersion: 2010-09-09

Description: Create an ECR Repository

Resources:
  ContainerRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: dotnet-webapp
      ImageScanningConfiguration:
        ScanOnPush: false
      ImageTagMutability: MUTABLE # IMMUTABLE
      EmptyOnDelete: true
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep last 3 images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 3
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }

Outputs:
  RepositoryUri:
    Description: ECR Repository URI
    Value: !GetAtt ContainerRepository.RepositoryUri
  RepositoryName:
    Description: ECR Repository Name
    Value: !Ref ContainerRepository
